# Generated by Django 3.0.5 on 2022-04-01 21:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('BBA', 'BBA'), ('English', 'English'), ('Math', 'Math'), ('Bangla', 'Bangla')], max_length=100),
        ),
    ]
