# Generated by Django 3.0.5 on 2022-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_answersheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='mcqMarks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
