# Generated by Django 3.0.5 on 2022-04-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20220411_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
