# Generated by Django 3.0.5 on 2022-04-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_answersheet_is_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
