# Generated by Django 3.0.5 on 2022-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20220412_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Strict', 'Strict'), ('Warning', 'Warning'), ('Open Book', 'Open Book')], default='Strict', max_length=50),
        ),
    ]
