# Generated by Django 3.0.5 on 2022-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Strict', 'Strict'), ('Warning', 'Warning'), ('Notify', 'Notify'), ('Open Book', 'Open Book'), ('Capture', 'Capture'), ('Record', 'Record')], default='Strict', max_length=50),
        ),
    ]
