# Generated by Django 3.0.5 on 2022-04-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_expel'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='unfocus',
            field=models.IntegerField(default=0),
        ),
    ]
