# Generated by Django 3.0.5 on 2022-04-07 17:02

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20220401_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.get_dir),
        ),
    ]
