# Generated by Django 3.0.5 on 2022-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20220407_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
