# Generated by Django 3.0.5 on 2022-04-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_is_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_recorded',
            field=models.BooleanField(default=False),
        ),
    ]
