# Generated by Django 3.0.5 on 2022-04-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_is_recorded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_recorded',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_trained',
        ),
    ]
